### ISSUE TITLE
Nice job

### ISSUE THREAD

**Issue by adammenges** [TheFrenchGuy/TimeLeftUntil#1]
Would've sent ya an email or DM but couldn't find a way, so I'll just stick it in an issue. 

Dope app. Nice job!

---

A small thing while we're here:

<img width="104" alt="CleanShot 2021-07-20 at 09 51 54@2x" src="https://user-images.githubusercontent.com/817438/126364195-d0344490-4e95-4fee-a2a0-65edca920429.png">

A white icon would be great.

**Comment by TheFrenchGuy** [comment]
Fixed in the latest commit wasn't able to use the same icon but instead used the lightbulb SF symbol icon, since was unable to have a satisfactory results  to get the color of the menubar in macOS 

Thanks by the way !!!
